spring.application.name=mall-auth-server
spring.cloud.nacos.discovery.server-addr=127.0.0.1:8848
spring.cloud.nacos.config.server-addr=127.0.0.1:8848
spring.config.import=optional:nacos:${spring.application.name}.properties

server.port=20000

spring.redis.host=192.168.88.128
spring.redis.port=6379
