spring.application.name=mall-order
spring.cloud.nacos.discovery.server-addr=127.0.0.1:8848
spring.cloud.nacos.config.server-addr=127.0.0.1:8848
spring.config.import=optional:nacos:${spring.application.name}.properties

server.servlet.context-path=/

spring.rabbitmq.host=192.168.88.128
spring.rabbitmq.port=5672
spring.rabbitmq.virtual-host=/

# ?????????? Exchange ????
spring.rabbitmq.publisher-confirm=true

# ????????? Exchange ??? Queue ??????
spring.rabbitmq.publisher-returns=true

spring.rabbitmq.template.mandatory=true

# ?? ACK????????????
spring.rabbitmq.listener.simple.acknowledge-mode=manual

spring.thymeleaf.cache=false
